language: android
dist: precise
sudo: required
jdk:
- oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=26
  - ANDROID_API_LEVEL_22=22
  - ANDROID_BUILD_TOOLS_VERSION=26.0.2
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - ANDROID_TARGET=android-26
  - ADB_INSTALL_TIMEOUT=20

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - tools
  - android-$ANDROID_API_LEVEL
  - addon-google_apis-google-$ANDROID_API_LEVEL
  - extra-google-google_play_services
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - android-sdk-license-.+
  - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL_22
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-preview-license-52d11cd2
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
- chmod +x ./scripts/ci/before_install.sh
- chmod +x ./scripts/ci/install.sh
- chmod +x ./scripts/ci/after_script.sh
- chmod +x ./scripts/ci/after_success.sh
- ./scripts/ci/before_install.sh

script: ./scripts/ci/install.sh

after_script: ./scripts/ci/after_script.sh

after_success: ./scripts/ci/after_success.sh

notifications:
  slack:
    secure: ZBi4hBzplJNK8GXau+pKqIMjfeJCSDKSmeXYy8mr3/LsW/+OVhVNM3Exz97eNA+JN1W+oerIgZn6MY9VyN6U4QSxVblawvTWewPafsZ8z2DSQ2yYEbiziqhCOdXPTk3dKwcSHu371+xYBIPRIPXPz0hd4rTnjEchtd12gNC24J6hg/jpPpMJnsWMl2lHwNzsVZTp3pj37zVIF9pdCncURiZF7pMzPeP6XUCNryDExnbixC+gmx8aeDRtowvH/pwrSzLKr7Rr79X9PnYhjntPVDcLlzEf6ekEMzyAxNOxnINN0pxDziQaGBNNQ3/TApo9OthmKArtktNmEW3uBqVZo8I1rBOK3Kc0j+McmnMLSuOxas1Z3Qv6gkgeci2069xI+Ibzq8gVJRbcNB1IKtG5vzLn5ueAek7AJCTjsbvwC+MipFea74aWNNzb+uzJt0QCh6wGdtwZeJODgtKi8MML4eWORpew/pK4hQrOFxObshjQzF0IeneG2FNbNr7bXHJI6VCZEwJjQXptB5JGKU4vkf5iGT+Mb/1BNBieskNGJVeYjSQsviRLO/RZfiyQNddOJnw8MjwN9SUuWEKqo0MFBAu8pxZgeOf3ysVqJ1tuYlIG5eFx74gPi4DKYmq331UaQP2y/E8bH8c0bEg/AlEpxLcAxZWcZ2YSg2xopo6JhZg=
